### ISSUE TITLE
As an SBA user, I'd like the pilot process to run as a web application

### ISSUE THREAD

**Issue by bsweger** [18F/data-act-pilot#90]
Acceptance Criteria:

- [ ] "Hello Data World" website runs locally 

Tasks:

- [x] Configure serving a flask app.
- [x] Serve static assets
- [x] Password protect the site
- [x] Set up a single html template for the home page.

Questions:
- Is there any reason we would need persistent storage, a database?

**Comment by bsweger** [comment]
Use the screencast from the March workshop as a guideline

**Comment by jtag** [comment]
Hopping in here. Let's make sure the user experience and design of this solid. It would be a huge win for this to be a wow, pleasurable experience since it will be a showcase pilot.

"Website will run initial validations on the data file and report status"  seems like could include many use cases for the types of validation errors sent back to the user.

**Comment by ngupta02** [comment]
To Jesse's point, I actually think this is key.

**Comment by bsweger** [comment]
Marco's officially on the job now. :) 

Confirmed that we have budget for a UX team resource if we need that. Thanks, Jesse!

**Comment by bsweger** [comment]
Removed the task for transferring SQL to SBA, since that's a separate story now.

**Comment by msecret** [comment]
Question: should we create a new repository to hold this we app?

**Comment by bsweger** [comment]
Good question. I'd be interested to hear your tech perspective. We've been giving out the link to this repo as the place to watch the pilot's progress, so there's a practical reason to keep the work here.
